baseURL = "https://hugo-modus.vercel.app/"
title = "hugo-modus"
copyright = "&copy; 2025"
theme = "modus"

[params]
description = "An opinionated Hugo theme using the [colour palette of the Modus themes](https://protesilaos.com/emacs/modus-themes-colors)."

[markup]
  [markup.highlight]
    noClasses = false

[menus]
  [[menus.main]]
    name = "GitHub"
    url = "https://github.com/goofansu/hugo-modus"
