baseURL = "https://hugo-modus.vercel.app/"
title = "Modus"
copyright = "Copyright &copy; 2024 Modus contributors."

disableKinds = ["section", "taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en-US"
theme = "modus"

[params]
description = "A Hugo theme inspired by [Modus themes](https://protesilaos.com/emacs/modus-themes)."

[markup]
  [markup.highlight]
    noClasses = false

[menus]
  [[menus.main]]
  name = "Subscribe"
  url = "/index.xml"
